### ISSUE TITLE
help/reference: what is the correct way to retrieve the output of a pipe with async steps?

### ISSUE THREAD

**Issue by osher** [apigee-127/bagpipes#13]
Hi.

I got the idea of 

```
var bpCfg = require('config');
var bagpipes = require('bagpipes').create( bpCfg.pipes, bpCfg.options );
bagpipes.play(bagpipes.getPipe(pipeName), ctx)

//wait
ctx.output
```

But I'm having trouble to figure where do I deliver the final-result callback...

I saw the project in use in swagger-node-runner, and I saw there something with _finish - this doesn't look like a finished API. Is the project immature? I hope not ...  ..I mean I hope it is mature...

Help?

**Comment by theganyo** [comment]
Hey osher,

You have to treat a pipe as an async process. Thus, the end fitting of the pipe should do whatever you want it to. I considered adding a notification or other API for the completion of the pipe, but it just seemed redundant to simply adding a fitting at the end. Do you think that's confusing?

Scott

**Comment by theganyo** [comment]
BTW: I just remember that this "issue" is already mentioned here: https://github.com/apigee-127/bagpipes/issues/11, so I'm going to close this in favor of that one. If you have specific ideas around what would make the most sense to you, please comment there.

**Comment by osher** [comment]
roger that. I'll be at #11
