### ISSUE TITLE
user fitting - save to output

### ISSUE THREAD

**Issue by Mattzr** [apigee-127/bagpipes#3]
Hi,

Me again ! When I try to save data on the context doing context.output = "something", I can't get it from the following user type fitting.

1st fitting code:

```
   context.output = "something"
   return cb(null, context.output);  // Not sure why we need to pass the response again
```

The following user fitting does context.input but this is empty.

(I tried adding the below in the swagger file but same story
    transformRetailOrder: # <---- this is the 2nd fitting invoked
        name: transformRetailOrder
        input:
          retailOrders:
            name: '*' # wildcard to pick entire object
            default: NOT_FOUND
)

**Comment by theganyo** [comment]
In general, you wouldn't set context.output directly. When a fitting returns using:

```
cb(null, 'something')
```

The 'something' is automatically placed into the output. Does that help at all?

BTW: Have you take a look at the example projects here? https://github.com/apigee-127/swagger-pipes-examples

**Comment by Mattzr** [comment]
I looked at the example projects but no fitting adds data in the output.

Ok then I removed the context.output. How would you then retrieve this "something" from the following user type fitting ?

**Comment by Mattzr** [comment]
This works now thanks for the fix
