### ISSUE TITLE
Cannot find module even though it exists

### ISSUE THREAD

**Issue by eladsulami** [apigee-127/bagpipes#34]
since 1.1.1 for some fittings we get this error,
it depends on the length of a fitting.

I commented on it in:
https://github.com/apigee-127/bagpipes/commit/c14ffd2605b71d3af8931388010ec5d80706d117?_pjax=%23js-repo-pjax-container

**Comment by theganyo** [comment]
I'm very sorry about this. That PR ^ broke it. The change will have to be rolled back.

**Comment by theganyo** [comment]
This should be fixed now. Please try 0.1.2.
