### ISSUE TITLE
Lodash vulnerability

### ISSUE THREAD

**Issue by jwmarshall** [apigee-127/bagpipes#36]
FYI you should update loadash to >=4.17.5 due to a prototype pollution vulnerability.

See: https://nodesecurity.io/advisories/577

**Comment by ghost** [comment]
Any update on this?

This should be fixed asap!

**Comment by runjak** [comment]
If I'm correct `lodash` in the `package.json` is ok, but the version of `machinepack-http` still depends on an outdated version of `lodash` - so it would make sense to update there.

**Comment by theganyo** [comment]
Updated in 0.2.0.
