### ISSUE TITLE
PR creation permission

### ISSUE THREAD

**Issue by danielgolub** [apigee-127/bagpipes#63]
I'd like to push a PR with security patch for review, but get a permissions error.
Is it restricted for some reason?
<img width="798" alt="image" src="https://github.com/apigee-127/bagpipes/assets/1869601/59c49271-81de-424d-99be-c8d75d5ae3c6">

<img width="1202" alt="image" src="https://github.com/apigee-127/bagpipes/assets/1869601/21cc7889-64fa-4df3-b83b-17d31ab13c37">

**Comment by theganyo** [comment]
You can't push any commits, you'd have to open a PR from a fork. That said, I just merged a bunch of PRs from dependabot... Perhaps that addresses your security issues?
